-- =============================================================================
-- Objets d'audit qualité
-- Additif et rejouable : aucune table métier ou du pipeline n'est supprimée.
-- =============================================================================

CREATE TABLE IF NOT EXISTS tp3_quality_run (
    run_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase           VARCHAR(30) NOT NULL,
    executed_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    total_offres    BIGINT NOT NULL DEFAULT 0,
    notes           TEXT,
    CONSTRAINT ck_tp3_quality_run_phase
        CHECK (phase IN (
            'before_cleaning', 'after_cleaning',
            'after_pipeline_reload', 'monitoring'
        ))
);

ALTER TABLE tp3_quality_run
    ADD COLUMN IF NOT EXISTS baseline_run_id BIGINT;

ALTER TABLE tp3_quality_run
    DROP CONSTRAINT IF EXISTS ck_tp3_quality_run_phase;

ALTER TABLE tp3_quality_run
    ADD CONSTRAINT ck_tp3_quality_run_phase
        CHECK (phase IN (
            'before_cleaning', 'after_cleaning',
            'after_pipeline_reload', 'monitoring'
        ));

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_tp3_quality_run_baseline'
          AND conrelid = 'tp3_quality_run'::regclass
    ) THEN
        ALTER TABLE tp3_quality_run
            ADD CONSTRAINT fk_tp3_quality_run_baseline
            FOREIGN KEY (baseline_run_id)
            REFERENCES tp3_quality_run (run_id)
            ON DELETE SET NULL;
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS tp3_quality_result (
    run_id              BIGINT NOT NULL,
    control_code        VARCHAR(10) NOT NULL,
    dimension           VARCHAR(20) NOT NULL,
    control_label       TEXT NOT NULL,
    severity            VARCHAR(10) NOT NULL,
    anomaly_count       BIGINT NOT NULL,
    population_count    BIGINT NOT NULL,
    anomaly_rate_pct    NUMERIC(8,4) NOT NULL,
    result_status       VARCHAR(10) NOT NULL,
    decision            TEXT NOT NULL,
    PRIMARY KEY (run_id, control_code),
    CONSTRAINT fk_tp3_quality_result_run
        FOREIGN KEY (run_id) REFERENCES tp3_quality_run (run_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_tp3_quality_dimension
        CHECK (dimension IN (
            'completude', 'unicite', 'validite', 'coherence', 'integrite'
        )),
    CONSTRAINT ck_tp3_quality_severity
        CHECK (severity IN ('INFO', 'LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT ck_tp3_quality_result_status
        CHECK (result_status IN ('PASS', 'WARN', 'FAIL'))
);

CREATE TABLE IF NOT EXISTS tp3_cleaning_log (
    cleaning_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    executed_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    rule_code       VARCHAR(20) NOT NULL,
    table_name      VARCHAR(100) NOT NULL,
    record_key      TEXT NOT NULL,
    column_name     VARCHAR(100) NOT NULL,
    old_value       TEXT,
    new_value       TEXT,
    justification   TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tp3_quality_result_dimension
    ON tp3_quality_result (run_id, dimension);

CREATE INDEX IF NOT EXISTS idx_tp3_cleaning_log_rule
    ON tp3_cleaning_log (rule_code, executed_at DESC);

CREATE OR REPLACE VIEW tp3_quality_current AS
WITH
totals AS (
    SELECT
        (SELECT count(*) FROM offre) AS offres,
        (SELECT count(*) FROM entreprise) AS entreprises,
        (SELECT count(*) FROM commune) AS communes,
        (SELECT count(*) FROM competence) AS competences,
        (SELECT count(*) FROM exigence_offre) AS exigences,
        (SELECT count(*) FROM tp2_offre_enrichment) AS enrichissements
),
checks (
    control_code, dimension, control_label, severity,
    anomaly_count, population_count, decision
) AS (
    SELECT 'C01', 'completude', 'Description absente', 'LOW',
        count(*) FILTER (WHERE description IS NULL OR btrim(description) = ''),
        count(*),
        'Conserver NULL : aucune description fiable ne peut être inventée.'
    FROM offre
    UNION ALL
    SELECT 'C02', 'completude', 'Durée de travail absente', 'LOW',
        count(*) FILTER (
            WHERE duree_travail IS NULL OR btrim(duree_travail) = ''
        ),
        count(*),
        'Conserver NULL et mesurer : donnée facultative dans la source.'
    FROM offre
    UNION ALL
    SELECT 'C03', 'completude', 'Salaire annuel estimé absent', 'INFO',
        count(*) FILTER (WHERE salaire_brut_annuel_estime IS NULL),
        count(*),
        'Conserver NULL : pas d''imputation statistique sans règle métier.'
    FROM offre
    UNION ALL
    SELECT 'C04', 'completude', 'Offre sans compétence', 'MEDIUM',
        count(*) FILTER (
            WHERE NOT EXISTS (
                SELECT 1 FROM exigence_offre eo
                WHERE eo.offre_id = offre.offre_id
            )
        ),
        count(*),
        'Conserver l''offre et signaler la lacune ; ne pas créer de compétence.'
    FROM offre
    UNION ALL
    SELECT 'C05', 'completude', 'Commune sans coordonnées complètes', 'LOW',
        count(*) FILTER (WHERE latitude IS NULL OR longitude IS NULL),
        count(*),
        'Compléter uniquement si l''API Géo fournit une coordonnée officielle.'
    FROM commune
    UNION ALL
    SELECT 'U01', 'unicite', 'Identifiant France Travail dupliqué', 'HIGH',
        count(*), (SELECT offres FROM totals),
        'Doit être nul : contrainte UNIQUE sur offre.source_offre_id.'
    FROM (
        SELECT source_offre_id FROM offre
        GROUP BY source_offre_id HAVING count(*) > 1
    ) duplicates
    UNION ALL
    SELECT 'U02', 'unicite', 'Compétence dupliquée après normalisation', 'MEDIUM',
        coalesce(sum(duplicate_count - 1), 0), (SELECT competences FROM totals),
        'Fusionner par lower(trim(espaces)) et conserver la plus ancienne clé.'
    FROM (
        SELECT count(*) AS duplicate_count
        FROM competence
        GROUP BY lower(
            regexp_replace(btrim(libelle_competence), '\s+', ' ', 'g')
        )
        HAVING count(*) > 1
    ) duplicates
    UNION ALL
    SELECT 'U03', 'unicite', 'Entreprise dupliquée après normalisation', 'MEDIUM',
        coalesce(sum(duplicate_count - 1), 0), (SELECT entreprises FROM totals),
        'Fusionner par lower(trim(espaces)) et conserver la plus ancienne clé.'
    FROM (
        SELECT count(*) AS duplicate_count
        FROM entreprise
        WHERE raison_sociale IS NOT NULL
        GROUP BY lower(
            regexp_replace(btrim(raison_sociale), '\s+', ' ', 'g')
        )
        HAVING count(*) > 1
    ) duplicates
    UNION ALL
    SELECT 'V01', 'validite', 'Date de publication future', 'HIGH',
        count(*) FILTER (WHERE date_publication > current_date),
        count(*),
        'Rejeter : une offre ne peut pas être publiée dans le futur.'
    FROM offre
    UNION ALL
    SELECT 'V02', 'validite', 'Salaire annuel nul ou négatif', 'HIGH',
        count(*) FILTER (WHERE salaire_brut_annuel_estime = 0),
        count(*),
        'Mettre à NULL et corriger le parseur ; les négatifs sont bloqués par CHECK.'
    FROM offre
    UNION ALL
    SELECT 'V03', 'validite', 'Salaire annuel hors plage plausible', 'MEDIUM',
        count(*) FILTER (
            WHERE salaire_brut_annuel_estime > 0
              AND salaire_brut_annuel_estime < 1000
               OR salaire_brut_annuel_estime > 250000
        ),
        count(*),
        'Mettre à NULL ; conserver le texte source dans le Data Lake.'
    FROM offre
    UNION ALL
    SELECT 'V04', 'validite', 'Format de code géographique ou ROME invalide', 'HIGH',
        (
            SELECT count(*) FROM commune
            WHERE code_insee !~ '^[0-9][0-9AB][0-9]{3}$'
               OR code_postal !~ '^[0-9]{5}$'
        ) + (
            SELECT count(*) FROM metier_rome
            WHERE rome_code !~ '^[A-Z][0-9]{4}$'
        ),
        (SELECT communes FROM totals) + (SELECT count(*) FROM metier_rome),
        'Rejeter à l''ingestion ; les CHECK PostgreSQL constituent le garde-fou.'
    UNION ALL
    SELECT 'H01', 'coherence', 'Entreprise incohérente avec son anonymat', 'HIGH',
        count(*) FILTER (
            WHERE (entreprise_anonyme AND raison_sociale IS NOT NULL)
               OR (
                    NOT entreprise_anonyme
                    AND (raison_sociale IS NULL OR btrim(raison_sociale) = '')
               )
        ),
        count(*),
        'Corriger le booléen ou le nom selon la valeur source disponible.'
    FROM entreprise
    UNION ALL
    SELECT 'H02', 'coherence', 'Enrichissement communal non apparié', 'MEDIUM',
        count(*) FILTER (WHERE commune_reference_status <> 'matched'),
        count(*),
        'Conserver le statut et investiguer le code INSEE ; pas d''imputation.'
    FROM tp2_offre_enrichment
    UNION ALL
    SELECT 'H03', 'coherence', 'Offre sans ligne d''enrichissement du pipeline', 'INFO',
        count(*) FILTER (
            WHERE NOT EXISTS (
                SELECT 1 FROM tp2_offre_enrichment e
                WHERE e.source_offre_id = offre.source_offre_id
            )
        ),
        count(*),
        'Toléré pour les offres de démonstration ; aucune fausse jointure.'
    FROM offre
    UNION ALL
    SELECT 'I01', 'integrite', 'Référence orpheline dans offre', 'HIGH',
        count(*), (SELECT offres FROM totals),
        'Doit être nul grâce aux trois clés étrangères de offre.'
    FROM offre o
    LEFT JOIN commune c ON c.code_insee = o.code_insee
    LEFT JOIN entreprise e ON e.entreprise_id = o.entreprise_id
    LEFT JOIN metier_rome m ON m.rome_code = o.rome_code
    WHERE c.code_insee IS NULL
       OR e.entreprise_id IS NULL
       OR m.rome_code IS NULL
    UNION ALL
    SELECT 'I02', 'integrite', 'Association offre-compétence orpheline', 'HIGH',
        count(*), (SELECT exigences FROM totals),
        'Doit être nul grâce aux clés étrangères de exigence_offre.'
    FROM exigence_offre eo
    LEFT JOIN offre o ON o.offre_id = eo.offre_id
    LEFT JOIN competence c ON c.competence_id = eo.competence_id
    WHERE o.offre_id IS NULL OR c.competence_id IS NULL
)
SELECT
    control_code,
    dimension,
    control_label,
    severity,
    anomaly_count::bigint,
    population_count::bigint,
    round(
        CASE WHEN population_count = 0 THEN 0
             ELSE 100.0 * anomaly_count / population_count END,
        4
    ) AS anomaly_rate_pct,
    CASE
        WHEN anomaly_count = 0 THEN 'PASS'
        WHEN severity = 'HIGH' THEN 'FAIL'
        ELSE 'WARN'
    END AS result_status,
    decision
FROM checks;

CREATE OR REPLACE FUNCTION tp3_execute_quality_audit(
    p_phase VARCHAR,
    p_notes TEXT DEFAULT NULL,
    p_baseline_run_id BIGINT DEFAULT NULL
) RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_run_id BIGINT;
BEGIN
    IF p_phase NOT IN (
        'before_cleaning', 'after_cleaning',
        'after_pipeline_reload', 'monitoring'
    ) THEN
        RAISE EXCEPTION 'Invalid quality audit phase: %', p_phase;
    END IF;

    IF p_phase IN ('after_cleaning', 'after_pipeline_reload')
       AND p_baseline_run_id IS NULL THEN
        RAISE EXCEPTION 'A baseline run is required for phase %', p_phase;
    END IF;

    INSERT INTO tp3_quality_run (
        phase, baseline_run_id, total_offres, notes
    )
    VALUES (
        p_phase, p_baseline_run_id, (SELECT count(*) FROM offre), p_notes
    )
    RETURNING run_id INTO v_run_id;

    INSERT INTO tp3_quality_result (
        run_id, control_code, dimension, control_label, severity,
        anomaly_count, population_count, anomaly_rate_pct,
        result_status, decision
    )
    SELECT
        v_run_id, control_code, dimension, control_label, severity,
        anomaly_count, population_count, anomaly_rate_pct,
        result_status, decision
    FROM tp3_quality_current;

    RETURN v_run_id;
END;
$$;

CREATE OR REPLACE VIEW tp3_quality_latest_comparison AS
WITH ranked AS (
    SELECT
        r.*,
        row_number() OVER (
            PARTITION BY phase ORDER BY executed_at DESC, run_id DESC
        ) AS row_number
    FROM tp3_quality_run r
    WHERE phase = 'after_pipeline_reload'
),
after_run AS (
    SELECT run_id, baseline_run_id FROM ranked
    WHERE row_number = 1
)
SELECT
    before.control_code,
    before.dimension,
    before.control_label,
    before.severity,
    before.anomaly_count AS anomalies_before,
    after.anomaly_count AS anomalies_after,
    before.anomaly_count - after.anomaly_count AS corrected_count,
    before.anomaly_rate_pct AS rate_before_pct,
    after.anomaly_rate_pct AS rate_after_pct,
    after.result_status AS final_status
FROM tp3_quality_result before
JOIN after_run ar ON ar.baseline_run_id = before.run_id
JOIN tp3_quality_result after
    ON after.control_code = before.control_code
   AND after.run_id = ar.run_id;

CREATE OR REPLACE VIEW tp3_quality_cleaning_comparison AS
WITH ranked AS (
    SELECT
        r.*,
        row_number() OVER (
            ORDER BY executed_at DESC, run_id DESC
        ) AS row_number
    FROM tp3_quality_run r
    WHERE phase = 'after_cleaning'
),
after_run AS (
    SELECT run_id, baseline_run_id FROM ranked
    WHERE row_number = 1
)
SELECT
    before.control_code,
    before.dimension,
    before.control_label,
    before.severity,
    before.anomaly_count AS anomalies_before,
    after.anomaly_count AS anomalies_after,
    before.anomaly_count - after.anomaly_count AS corrected_count,
    before.anomaly_rate_pct AS rate_before_pct,
    after.anomaly_rate_pct AS rate_after_pct,
    after.result_status AS final_status
FROM tp3_quality_result before
JOIN after_run ar ON ar.baseline_run_id = before.run_id
JOIN tp3_quality_result after
    ON after.control_code = before.control_code
   AND after.run_id = ar.run_id;
