FROM apache/spark:3.5.3-scala2.12-java17-python3-ubuntu

USER root
WORKDIR /app
ENV PYTHONPATH=/app

COPY requirements-spark.txt /tmp/requirements-spark.txt
RUN python3 -m pip install --no-cache-dir -r /tmp/requirements-spark.txt

COPY . /app
