-- =============================================================================
-- TP Audit / Cartographie / Modélisation
-- Domaine : Emploi, marché du travail et recrutement
-- Objectif : identifier les tensions sur les compétences numériques par type
--            de contrat et bassin d'emploi.
-- SGBD cible : PostgreSQL 14+
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 1. Suppression propre préalable (ordre inverse des dépendances)
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS exigence_offre CASCADE;
DROP TABLE IF EXISTS offre CASCADE;
DROP TABLE IF EXISTS competence CASCADE;
DROP TABLE IF EXISTS metier_rome CASCADE;
DROP TABLE IF EXISTS entreprise CASCADE;
DROP TABLE IF EXISTS commune CASCADE;

-- -----------------------------------------------------------------------------
-- 2. Création des tables, contraintes d'intégrité et clés étrangères
-- -----------------------------------------------------------------------------

-- Référentiel géographique (Base Adresse Nationale / codes commune INSEE)
CREATE TABLE commune (
    code_insee   CHAR(5)        PRIMARY KEY,
    code_postal  VARCHAR(5)     NOT NULL,
    nom_commune  VARCHAR(100)   NOT NULL,
    latitude     NUMERIC(9,6),
    longitude    NUMERIC(9,6),
    CONSTRAINT ck_commune_code_insee_format
        CHECK (code_insee ~ '^[0-9][0-9AB][0-9]{3}$'),
    CONSTRAINT ck_commune_code_postal_format
        CHECK (code_postal ~ '^[0-9]{5}$'),
    CONSTRAINT ck_commune_nom_non_vide
        CHECK (btrim(nom_commune) <> ''),
    CONSTRAINT ck_commune_latitude
        CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_commune_longitude
        CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

-- Entreprises recruteuses, avec gestion explicite de l'anonymat
CREATE TABLE entreprise (
    entreprise_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raison_sociale       VARCHAR(150),
    entreprise_anonyme   BOOLEAN NOT NULL DEFAULT FALSE,
    -- Une entreprise non anonyme doit obligatoirement avoir une raison sociale renseignée.
    CONSTRAINT ck_entreprise_raison_sociale_coherente
        CHECK (
            entreprise_anonyme = TRUE
            OR (raison_sociale IS NOT NULL AND btrim(raison_sociale) <> '')
        )
);

-- Référentiel ROME 4.0 (nomenclature des métiers France Travail)
CREATE TABLE metier_rome (
    rome_code               VARCHAR(5) PRIMARY KEY,
    libelle_fiche_metier    VARCHAR(150) NOT NULL,
    domaine_professionnel   VARCHAR(150) NOT NULL,
    CONSTRAINT ck_metier_rome_code_format
        CHECK (rome_code ~ '^[A-Z][0-9]{4}$'),
    CONSTRAINT ck_metier_rome_libelle_non_vide
        CHECK (btrim(libelle_fiche_metier) <> '')
);

-- Compétences techniques (savoir-faire) et comportementales (savoir-être)
CREATE TABLE competence (
    competence_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle_competence    VARCHAR(150) NOT NULL UNIQUE,
    type_competence        VARCHAR(20) NOT NULL,
    CONSTRAINT ck_competence_type_valide
        CHECK (type_competence IN ('Savoir-faire', 'Savoir-être'))
);

-- Offres d'emploi (fait central) issues de l'API France Travail
CREATE TABLE offre (
    offre_id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_offre_id                VARCHAR(20)  NOT NULL UNIQUE,
    libelle_poste                  VARCHAR(200) NOT NULL,
    description                    TEXT,
    date_publication                DATE NOT NULL,
    type_contrat                   VARCHAR(5) NOT NULL,
    duree_travail                   VARCHAR(100),
    salaire_brut_annuel_estime      NUMERIC(10,2),
    rome_code                      VARCHAR(5) NOT NULL,
    entreprise_id                  BIGINT NOT NULL,
    code_insee                     CHAR(5) NOT NULL,
    CONSTRAINT fk_offre_metier_rome
        FOREIGN KEY (rome_code) REFERENCES metier_rome (rome_code)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_offre_entreprise
        FOREIGN KEY (entreprise_id) REFERENCES entreprise (entreprise_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_offre_commune
        FOREIGN KEY (code_insee) REFERENCES commune (code_insee)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT ck_offre_source_non_vide
        CHECK (btrim(source_offre_id) <> ''),
    CONSTRAINT ck_offre_libelle_non_vide
        CHECK (btrim(libelle_poste) <> ''),
    CONSTRAINT ck_offre_type_contrat_valide
        CHECK (type_contrat IN ('CDI', 'CDD', 'MIS', 'SAI', 'CCE')),
    CONSTRAINT ck_offre_salaire_positif
        CHECK (salaire_brut_annuel_estime IS NULL OR salaire_brut_annuel_estime >= 0)
);

-- Table d'association N,N portant l'attribut d'exigence de la compétence
CREATE TABLE exigence_offre (
    offre_id         BIGINT NOT NULL,
    competence_id    BIGINT NOT NULL,
    statut_exigence   VARCHAR(1) NOT NULL,
    PRIMARY KEY (offre_id, competence_id),
    CONSTRAINT fk_exigence_offre_offre
        FOREIGN KEY (offre_id) REFERENCES offre (offre_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_exigence_offre_competence
        FOREIGN KEY (competence_id) REFERENCES competence (competence_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT ck_exigence_offre_statut_valide
        CHECK (statut_exigence IN ('E', 'S'))
);

-- -----------------------------------------------------------------------------
-- 3. Index B-Tree pour optimiser les jointures et les filtres récurrents
-- -----------------------------------------------------------------------------

CREATE INDEX idx_offre_rome_code       ON offre USING btree (rome_code);
CREATE INDEX idx_offre_type_contrat    ON offre USING btree (type_contrat);
CREATE INDEX idx_offre_code_insee      ON offre USING btree (code_insee);
CREATE INDEX idx_offre_date_publication ON offre USING btree (date_publication);
CREATE INDEX idx_offre_commune_contrat ON offre USING btree (code_insee, type_contrat);
CREATE INDEX idx_exigence_offre_competence ON exigence_offre USING btree (competence_id);
CREATE INDEX idx_commune_code_postal   ON commune USING btree (code_postal);
CREATE INDEX idx_entreprise_raison_sociale ON entreprise USING btree (raison_sociale);

-- -----------------------------------------------------------------------------
-- 4. Jeu de données de test cohérent
-- -----------------------------------------------------------------------------

-- 2 communes (bassins d'emploi)
INSERT INTO commune (code_insee, code_postal, nom_commune, latitude, longitude) VALUES
    ('44172', '44980', 'Sainte-Luce-sur-Loire', 47.249400, -1.486200),
    ('75111', '75011', 'Paris 11e Arrondissement', 48.857700, 2.379900);

-- 2 entreprises, dont une anonyme
INSERT INTO entreprise (raison_sociale, entreprise_anonyme) VALUES
    ('TECH INNOVATION', FALSE),
    (NULL, TRUE);

-- 2 fiches métier ROME
INSERT INTO metier_rome (rome_code, libelle_fiche_metier, domaine_professionnel) VALUES
    ('M1805', 'Études et développement informatique', 'Systèmes d''information et télécommunications'),
    ('M1806', 'Conseil et maîtrise d''ouvrage en systèmes d''information', 'Systèmes d''information et télécommunications');

-- 4 compétences (savoir-faire et savoir-être)
INSERT INTO competence (libelle_competence, type_competence) VALUES
    ('Langage SQL', 'Savoir-faire'),
    ('Concevoir une base de données', 'Savoir-faire'),
    ('Python', 'Savoir-faire'),
    ('Travail en équipe', 'Savoir-être');

-- 3 offres d'emploi
INSERT INTO offre (
    source_offre_id, libelle_poste, description, date_publication,
    type_contrat, duree_travail, salaire_brut_annuel_estime,
    rome_code, entreprise_id, code_insee
) VALUES
    ('178XYZW',
     'Data Engineer / DBA PostgreSQL (F/H)',
     'Au sein du pôle Data, vous concevez et maintenez les pipelines de données.',
     DATE '2026-09-18', 'CDI', '35H Horaires normaux', 41500.00,
     'M1805',
     (SELECT entreprise_id FROM entreprise WHERE raison_sociale = 'TECH INNOVATION'),
     '44172'),
    ('178ABCD',
     'Consultant SI Data (F/H)',
     'Vous accompagnez nos clients dans la modernisation de leur système d''information.',
     DATE '2026-09-10', 'CDD', '39H Horaires normaux', 46000.00,
     'M1806',
     (SELECT entreprise_id FROM entreprise WHERE entreprise_anonyme = TRUE),
     '75111'),
    ('178EFGH',
     'Administrateur de bases de données (F/H)',
     'Vous administrez et sécurisez les bases PostgreSQL de production.',
     DATE '2026-09-05', 'CDI', '35H Horaires normaux', 39000.00,
     'M1805',
     (SELECT entreprise_id FROM entreprise WHERE raison_sociale = 'TECH INNOVATION'),
     '75111');

-- Liaisons offre/compétence avec statut d'exigence
INSERT INTO exigence_offre (offre_id, competence_id, statut_exigence)
SELECT o.offre_id, c.competence_id, v.statut_exigence
FROM (VALUES
        ('178XYZW', 'Langage SQL', 'E'),
        ('178XYZW', 'Concevoir une base de données', 'E'),
        ('178XYZW', 'Python', 'S'),
        ('178ABCD', 'Langage SQL', 'E'),
        ('178ABCD', 'Travail en équipe', 'E'),
        ('178EFGH', 'Langage SQL', 'E'),
        ('178EFGH', 'Concevoir une base de données', 'E'),
        ('178EFGH', 'Travail en équipe', 'S')
     ) AS v(source_offre_id, libelle_competence, statut_exigence)
JOIN offre o       ON o.source_offre_id = v.source_offre_id
JOIN competence c  ON c.libelle_competence = v.libelle_competence;

-- -----------------------------------------------------------------------------
-- 5. Requêtes SQL avancées simulant le tableau de bord RH
-- -----------------------------------------------------------------------------

-- Requête 1 : compétences exigées ou souhaitées, agrégées par offre,
-- avec le métier ROME et le type de contrat, pour un export de dashboard RH.
SELECT
    o.source_offre_id,
    o.libelle_poste,
    mr.libelle_fiche_metier,
    o.type_contrat,
    nc.nom_commune,
    STRING_AGG(
        c.libelle_competence || ' (' || eo.statut_exigence || ')',
        ', ' ORDER BY eo.statut_exigence, c.libelle_competence
    ) AS competences_attendues
FROM offre o
JOIN metier_rome mr    ON mr.rome_code = o.rome_code
JOIN commune nc        ON nc.code_insee = o.code_insee
JOIN exigence_offre eo ON eo.offre_id = o.offre_id
JOIN competence c      ON c.competence_id = eo.competence_id
GROUP BY o.offre_id, o.source_offre_id, o.libelle_poste,
         mr.libelle_fiche_metier, o.type_contrat, nc.nom_commune
ORDER BY o.date_publication DESC;

-- Requête 2 : tension sur le marché par bassin d'emploi et type de contrat :
-- volume d'offres, salaire moyen estimé et compétence la plus demandée.
SELECT
    c.nom_commune,
    o.type_contrat,
    COUNT(DISTINCT o.offre_id)                       AS nombre_offres,
    ROUND(AVG(o.salaire_brut_annuel_estime), 2)      AS salaire_moyen_estime,
    STRING_AGG(DISTINCT comp.libelle_competence, ', ' ORDER BY comp.libelle_competence)
                                                       AS competences_demandees
FROM offre o
JOIN commune c              ON c.code_insee = o.code_insee
JOIN exigence_offre eo       ON eo.offre_id = o.offre_id
JOIN competence comp         ON comp.competence_id = eo.competence_id
WHERE eo.statut_exigence = 'E'
GROUP BY c.nom_commune, o.type_contrat
ORDER BY nombre_offres DESC, salaire_moyen_estime DESC;

COMMIT;
